apiVersion: v1
kind: Service
metadata:
  name: cdn-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: cdn
    version: blue # Switch between blue/green
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
