apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-service
  labels:
    app: cdn-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cdn-service
  template:
    metadata:
      labels:
        app: cdn-service
    spec:
      containers:
        - name: cdn-service
          image: cdn-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: cdn-config
                  key: redis_url
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: cdn-config
                  key: minio_endpoint
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 20
