openapi: 3.0.0
info:
  title: CDN Service API
  description: API documentation for the CDN Service with MinIO and AWS S3 support
  version: 1.3.0
  contact:
    name: Mesut GENEZ
    url: https://github.com/mstgnz/cdn

servers:
  - url: http://localhost:9090
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
        data:
          type: object

    HealthCheck:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, degraded]
        services:
          type: object
          properties:
            minio:
              type: string
            aws:
              type: string
            cache:
              type: string
        timestamp:
          type: string
          format: date-time

    UploadResponse:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
        data:
          type: object
          properties:
            minioUpload:
              type: string
              description: Minio upload status with size information
            minioResult:
              type: object
              description: Detailed result from Minio upload
            awsUpload:
              type: string
              description: AWS upload status (empty if not used)
            awsResult:
              type: string
              description: Detailed result from AWS upload (empty if not used)
            imageName:
              type: string
              description: Generated name of the uploaded file
            objectName:
              type: string
              description: Full path of the uploaded file
            link:
              type: string
              description: Public URL to access the file

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of all services
      tags:
        - health
      responses:
        "200":
          description: Health check results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthCheck"
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /metrics:
    get:
      summary: Prometheus metrics endpoint
      description: Returns Prometheus format metrics
      tags:
        - health
      responses:
        "200":
          description: Metrics in Prometheus format
          content:
            text/plain:
              schema:
                type: string

  /{bucket}/{path}:
    get:
      summary: Get original image
      tags:
        - image
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Image file
          content:
            image/*:
              schema:
                type: string
                format: binary
        "404":
          description: Image not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /{bucket}/w:{width}/{path}:
    get:
      summary: Get image with specific width
      tags:
        - image
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: width
          in: path
          required: true
          schema:
            type: integer
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Resized image
          content:
            image/*:
              schema:
                type: string
                format: binary

  /{bucket}/h:{height}/{path}:
    get:
      summary: Get image with specific height
      tags:
        - image
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: height
          in: path
          required: true
          schema:
            type: integer
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Resized image
          content:
            image/*:
              schema:
                type: string
                format: binary

  /{bucket}/w:{width}/h:{height}/{path}:
    get:
      summary: Get image with specific dimensions
      tags:
        - image
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: width
          in: path
          required: true
          schema:
            type: integer
        - name: height
          in: path
          required: true
          schema:
            type: integer
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Resized image
          content:
            image/*:
              schema:
                type: string
                format: binary

  /upload:
    post:
      summary: Upload image
      tags:
        - image
      security:
        - BearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                bucket:
                  type: string
                path:
                  type: string
                width:
                  type: integer
                height:
                  type: integer
                aws_upload:
                  type: boolean
              required:
                - file
                - bucket
      responses:
        "201":
          description: Upload successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /upload-url:
    post:
      summary: Upload file from URL
      tags:
        - image
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - bucket
                - url
              properties:
                aws_upload:
                  type: boolean
                  description: Upload to AWS S3
                path:
                  type: string
                  description: Optional path prefix for the file
                bucket:
                  type: string
                  description: Target bucket name
                url:
                  type: string
                  format: url
                  description: Source URL of the file to upload
      responses:
        "201":
          description: Upload successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /resize:
    post:
      summary: Resize existing image
      tags:
        - image
      security:
        - BearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                width:
                  type: integer
                height:
                  type: integer
              required:
                - file
      responses:
        "200":
          description: Resize successful
          content:
            image/*:
              schema:
                type: string
                format: binary

  /{bucket}/*:
    delete:
      summary: Delete image
      tags:
        - image
      security:
        - BearerAuth: []
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: aws_delete
          in: query
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: Delete successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /aws/bucket-list:
    get:
      summary: List AWS buckets
      tags:
        - aws
      security:
        - BearerAuth: []
      responses:
        "200":
          description: List of AWS buckets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    creationDate:
                      type: string
                      format: date-time

  /aws/{bucket}/exists:
    get:
      summary: Check if AWS bucket exists
      tags:
        - aws
      security:
        - BearerAuth: []
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Bucket existence check result
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean

  /aws/vault-list:
    get:
      summary: List AWS Glacier vaults
      tags:
        - aws
      security:
        - BearerAuth: []
      responses:
        "200":
          description: List of Glacier vaults
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    vaultName:
                      type: string
                    creationDate:
                      type: string
                      format: date-time

  /minio/bucket-list:
    get:
      summary: List MinIO buckets
      tags:
        - minio
      security:
        - BearerAuth: []
      responses:
        "200":
          description: List of MinIO buckets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    creationDate:
                      type: string
                      format: date-time

  /minio/{bucket}/exists:
    get:
      summary: Check if MinIO bucket exists
      tags:
        - minio
      security:
        - BearerAuth: []
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Bucket existence check result
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean

  /minio/{bucket}/create:
    get:
      summary: Create MinIO bucket
      tags:
        - minio
      security:
        - BearerAuth: []
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Bucket creation result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /minio/{bucket}/delete:
    get:
      summary: Delete MinIO bucket
      tags:
        - minio
      security:
        - BearerAuth: []
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Bucket deletion result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
